export const activities = [
  {
    name: "看AV",
    good: "释放压力，重铸自我",
    bad: "会被家人撞到",
  },
  {
    name: "组模型",
    good: "今天的喷漆会很完美",
    bad: "精神不集中板件被剪断了",
  },
  {
    name: "投稿情感区",
    good: "问题圆满解决",
    bad: "会被当事人发现",
  },
  {
    name: "逛匿名版",
    good: "今天也要兵库北",
    bad: "看到丧尸在晒妹",
  },
  {
    name: "和女神聊天",
    good: "女神好感度上升",
    bad: "我去洗澡了，呵呵",
  },
  {
    name: "啪啪啪",
    good: "啪啪啪啪啪啪啪",
    bad: "会卡在里面",
  },
  {
    name: "熬夜",
    good: "夜间的效率更高",
    bad: "明天有很重要的事",
  },
  {
    name: "锻炼",
    good: "八分钟给你比利般的身材",
    bad: "会拉伤肌肉",
  },
  {
    name: "散步",
    good: "遇到妹子主动搭讪",
    bad: "走路会踩到水坑",
  },
  {
    name: "打排位赛",
    good: "遇到大腿上分500",
    bad: "我方三人挂机",
  },
  {
    name: "汇报工作",
    good: "被夸奖工作认真",
    bad: "上班偷玩游戏被扣工资",
  },
  {
    name: "抚摸猫咪",
    good: "才不是特意蹭你的呢",
    bad: "死开！愚蠢的人类",
  },
  {
    name: "遛狗",
    good: "遇见女神遛狗搭讪",
    bad: "狗狗随地大小便被罚款",
  },
  {
    name: "烹饪",
    good: "黑暗料理界就由我来打败",
    bad: "难道这就是……仰望星空派？",
  },
  {
    name: "告白",
    good: "其实我也喜欢你好久了",
    bad: "对不起，你是一个好人",
  },
  {
    name: "求站内信",
    good: "最新种子入手",
    bad: "收到有码葫芦娃",
  },
  {
    name: "追新番",
    good: "完结之前我绝不会死",
    bad: "会被剧透",
  },
  {
    name: "打卡日常",
    good: "怒回首页",
    bad: "会被老板发现",
  },
  {
    name: "下副本",
    good: "配合默契一次通过",
    bad: "会被灭到散团",
  },
  {
    name: "抢沙发",
    good: "沙发入手弹无虚发",
    bad: "会被挂起来羞耻play",
  },
  {
    name: "网购",
    good: "商品大减价",
    bad: "问题产品需要退换",
  },
  {
    name: "跳槽",
    good: "新工作待遇大幅提升",
    bad: "再忍一忍就加薪了",
  },
  {
    name: "读书",
    good: "知识就是力量",
    bad: "注意力完全无法集中",
  },
  {
    name: "早睡",
    good: "早睡早起方能养生",
    bad: "会在半夜醒来，然后失眠",
  },
  {
    name: "写新的功能块",
    good: "毫无bug，完美完成",
    bad: "遇到连环bug",
  },
  {
    name: "逛街",
    good: "物美价廉大优惠",
    bad: "会遇到奸商",
  },
  {
    name: "写单元测试",
    good: "写单元测试将减少出错",
    bad: "写单元测试会降低你的开发效率",
  },
  {
    name: "洗澡",
    good: "你几天没洗澡了？",
    bad: "会把设计方面的灵感洗掉",
    weekend: true,
  },
  {
    name: "锻炼一下身体",
    good: "",
    bad: "能量没消耗多少，吃得却更多",
    weekend: true,
  },
  {
    name: "抽烟",
    good: "抽烟有利于提神，增加思维敏捷",
    bad: "除非你活够了，死得早点没关系",
    weekend: true,
  },
  { name: "白天上线", good: "今天白天上线是安全的", bad: "可能导致灾难性后果" },
  { name: "重构", good: "代码质量得到提高", bad: "你很有可能会陷入泥潭" },
  { name: "使用%t", good: "你看起来更有品位", bad: "别人会觉得你在装逼" },
  {
    name: "跳槽",
    good: "该放手时就放手",
    bad: "鉴于当前的经济形势，你的下一份工作未必比现在强",
  },
  { name: "招人", good: "你面前这位有成为牛人的潜质", bad: "这人会写程序吗？" },
  { name: "面试", good: "面试官今天心情很好", bad: "面试官不爽，会拿你出气" },
  {
    name: "提交辞职申请",
    good: "公司找到了一个比你更能干更便宜的家伙，巴不得你赶快滚蛋",
    bad: "鉴于当前的经济形势，你的下一份工作未必比现在强",
  },
  { name: "申请加薪", good: "老板今天心情很好", bad: "公司正在考虑裁员" },
  {
    name: "晚上加班",
    good: "晚上是程序员精神最好的时候",
    bad: "",
    weekend: true,
  },
  {
    name: "在妹子面前吹牛",
    good: "改善你矮穷挫的形象",
    bad: "会被识破",
    weekend: true,
  },
  { name: "LOL", good: "避免缓冲区溢出", bad: "强撸灰飞烟灭", weekend: true },
  {
    name: "浏览成人网站",
    good: "重拾对生活的信心",
    bad: "你会心神不宁",
    weekend: true,
  },
  { name: '命名变量"%v"', good: "", bad: "" },
  {
    name: "写超过%l行的方法",
    good: "你的代码组织的很好，长一点没关系",
    bad: "你的代码将混乱不堪，你自己都看不懂",
  },
  {
    name: "提交代码",
    good: "遇到冲突的几率是最低的",
    bad: "你遇到的一大堆冲突会让你觉得自己是不是时间穿越了",
  },
  {
    name: "代码复审",
    good: "发现重要问题的几率大大增加",
    bad: "你什么问题都发现不了，白白浪费时间",
  },
  {
    name: "开会",
    good: "写代码之余放松一下打个盹，有益健康",
    bad: "小心被扣屎盆子背黑锅",
  },
  {
    name: "打DOTA",
    good: "你将有如神助",
    bad: "你会被虐的很惨",
    weekend: true,
  },
  {
    name: "晚上上线",
    good: "晚上是程序员精神最好的时候",
    bad: "你白天已经筋疲力尽了",
  },
  {
    name: "修复BUG",
    good: "你今天对BUG的嗅觉大大提高",
    bad: "新产生的BUG将比修复的更多",
  },
  {
    name: "设计评审",
    good: "设计评审会议将变成头脑风暴",
    bad: "人人筋疲力尽，评审就这么过了",
  },
  { name: "需求评审", good: "", bad: "" },
  {
    name: "上微博",
    good: "今天发生的事不能错过",
    bad: "今天的微博充满负能量",
    weekend: true,
  },
  {
    name: "上AB站",
    good: "还需要理由吗？",
    bad: "满屏兄贵亮瞎你的眼",
    weekend: true,
  },
  {
    name: "玩FlappyBird",
    good: "今天破纪录的几率很高",
    bad: "除非你想玩到把手机砸了",
    weekend: true,
  },
];

export const tools = [
  "Eclipse写程序",
  "MSOffice写文档",
  "记事本写程序",
  "Windows8",
  "Linux",
  "MacOS",
  "IE",
  "Android设备",
  "iOS设备",
];

export const varNames = [
  "jieguo",
  "huodong",
  "pay",
  "expire",
  "zhangdan",
  "every",
  "free",
  "i1",
  "a",
  "virtual",
  "ad",
  "spider",
  "mima",
  "pass",
  "ui",
];
